### PR TITLE
Pause option added, Location structure Added , Hit function added

### PR DESCRIPTION
**Pull request by Siavoosh**
- Pause option added using key "p"
- Location structure Added instead of C & L for each item in game
- Hit function added to check if two location collide

special thanks to Jadi

### CODE REVIEW

**Comment by jadijadi** [comment]
Thanks. highly appreciated and needed. But please keep changes in atomic PRs so the viewers will understand the changes better . I will wait for your LOC pr, Pause PR and Hit functions (or maybe LOC & Hit in one PR if you prefer)

**Comment by Siavoosh** [comment]
Sure ! new PLs coming soon.

**Comment by Siavoosh** [comment]
sorry for my poor GH skills. i tried to do these changes in three seperated commits.

**Comment by jadijadi** [comment]
can you please close this PR and send only one for pause? that would be cleaner. Atomic PRs are better than a PR with 1 bug fix, 1 feature and 1 improvement.

**Comment by Siavoosh** [comment]
Yes Sure !, i'll try my best

**Pull request closed without merging**
