### PR TITLE
some bugs fixed and some features added (listed in the comment)

### PR DESCRIPTION
**Pull request by shayan15sa**
Hi jadi, special thanks for making this project. I've learned many new things so far.
Added features:
- ~~Now every bullet can destroy just one enemy~~
- Bullets destroy when hitting the ground
- A beep sound for shooting (Beep sound should be on in your terminal emulator)
- After enemies are hit they become a dead body and will be shown as "x" for one frame
Fixed bugs:
- the good bye message is now shown exactly in the middle of the screen

Again, thank you very much for anything you have taught me ❤️
shayan

### CODE REVIEW

**Comment by panoschagias** [comment]
I think the fact that "bullets" can hit more than one enemy is an intended feature.
That's the reason why their original shape was changed, to indicate their power.

**Comment by shayan15sa** [comment]
Oh, sorry I didn't know that.
So I'm gonna change the code and remove that part.
Thank for letting me know.

**Comment by jadijadi** [comment]
Thanks @shayan15sa Highly appreciated. I had a lot of changes on the code. Can you please rebase based on the new code and:
1. remove the beep. lets keep the game silent
2. remove the good bye message, we have a new fancy one
and I really loved the 'x' idea for dead enemies.

Sorry for the trouble. will merge sooner next time.

**Comment by shayan15sa** [comment]
i moved this PR [here](https://github.com/jadijadi/riverraidrust/pull/18)

**Pull request closed without merging**
