### PR TITLE
split project to different crates

### PR DESCRIPTION
**Pull request by tt-abdulhaq**
I just split the project to different crates. 
add `b` key code for champing 
I hope review this.

### CODE REVIEW

**Review by KohoolateSen — COMMENTED** [review]
This looks very clean , couldn't drawing also get split into another crate ?

**Comment by tt-abdulhaq** [comment]
> This looks very clean , couldn't drawing also get split into another crate ?

we can put drawing to another module  also, but I thing drawing is functionality of world. we can add `draw` as a method of world also.
please give me your suggestion.

**Comment by KohoolateSen** [comment]
> > This looks very clean , couldn't drawing also get split into another crate ?
> 
> we can put drawing to another module  also, but I thing drawing is functionality of world. we can add `draw` as a method of world also.
> please give me your suggestion.

Actually I'm new to Rust but I'll provide you my opinion (it's better to fulfill more research and do Q&A) but I think it will be more readable to keep drawing at a different module but so you can also open an issue and ask about this implementation.

**Comment by jadijadi** [comment]
Thank you very much @tt-abdulhaq . This is great. But.. the issue is code has changed a lot. Is it possible for you to redo this and send another PR? I would highly appreciated that and will merge that one first not to create this conflicts again. sorry for the hard task :)

**Comment by tt-abdulhaq** [comment]
> Thank you very much @tt-abdulhaq . This is great. But.. the issue is code has changed a lot. Is it possible for you to redo this and send another PR based on the latest code? I would highly appreciated that and will merge that one first not to create this conflicts again. sorry for the hard task :)
> 
> Hint.. maybe for others:
> 
> * In this case you have to redo the changes on your computer based on the latest code, and then do a "git push -ff"

Certainly!  I'll rework the changes on my end based on the latest code and submit another pull request. I'll make sure to resolve any conflicts that may arise and push the changes with 
I'll  `git push -ff`  for a smooth integration.

**Comment by tt-abdulhaq** [comment]
please review my PR on riverraidrust
https://github.com/jadijadi/riverraidrust/pull/53

**Pull request closed without merging**
